const data = {
    products: [
      {
        _id: '1',
        name: 'Adidas Unifornia Boot',
        category: 'Football',
        image: '/images/Adidas Uniforia.jpg',
        price: 311,
        countInStock: 10,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Australia Cricket Premium Jersey',
        category: 'Cricket',
        image: '/images/Australia Premium Jersey.jpg',
        price: 109,
        countInStock: 11,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Authentic Football Kit',
        category: 'Football',
        image: '/images/Authentic Football Kit.jpg',
        price: 99,
        countInStock: 7,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Barcelona Premium Kit',
        category: 'Football',
        image: '/images/Barcelona Premium Replica.jpg',
        price: 129,
        countInStock: 6,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Bangladesh Cricket WC2019 Premium',
        category: 'Cricket',
        image: '/images/BD-Cricket Jersey.jpg',
        price: 65,
        countInStock: 13,
        brand: 'New Balance',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Nike Premium Boot',
        category: 'Football',
        image: '/images/Best Nike Boot.jpg',
        price: 139,
        countInStock: 9,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'Burrusia Dortmund Premium Home Kit',
        category: 'Football',
        image: '/images/Burrusia Dortmond Home Kit.jpg',
        price: 135,
        countInStock: 0,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '8',
        name: 'Customized Cricket Jersey',
        category: 'Cricket',
        image: '/images/Customized Jersey Green.jpg',
        price: 139,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '9',
        name: 'Grey Nicols Kit',
        category: 'Cricket',
        image: '/images/GN-Premium Cricket Kit.jpg',
        price: 245,
        countInStock: 3,
        brand: 'Gray Nicols',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '10',
        name: 'New Balance Kit',
        category: 'Cricket',
        image: '/images/NB-Premium KIT Cricket.jpg',
        price: 189,
        countInStock: 2,
        brand: 'New Balance',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '11',
        name: 'Official New Zealand Jersey',
        category: 'Cricket',
        image: '/images/New Zealand.jpg',
        price: 129,
        countInStock: 1,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '12',
        name: 'Nike Premium Boot(Pink Edition)',
        category: 'Football',
        image: '/images/Nike Boot.jpg',
        price: 189,
        countInStock: 3,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '13',
        name: 'SG Cricket Kit',
        category: 'Cricket',
        image: '/images/SG-premium cricket kit.jpg',
        price: 210,
        countInStock: 0,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '14',
        name: 'New Balance Spike Boot White Edition',
        category: 'Cricket',
        image: '/images/NB-Cricket Boot.jpg',
        price: 139,
        countInStock: 4,
        brand: 'New Balance',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '15',
        name: 'SS Cricket Kit',
        category: 'Cricket',
        image: '/images/SS Original Master.jfif',
        price: 139,
        countInStock: 10,
        brand: 'SS',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;